version: "3.9"

services:
  backend:
    build: 
        context: .
        dockerfile: ./client/Dockerfile
    ports:
      - "5000:5000"
  frontend:
    image: nginx:alpine
    volumes:
      - ./client/ClientApp/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"